### PR TITLE
Fix 2 bugs in the pure_pursuit_controller that prevented it from working and add path pruning

### LINKED ISSUE #13: Pure pursuit controller not steering
Hi,

I'm following the navigation2 tutorial and and was testing the pure pursuit controller. It seems to me that the controllor is not steering. See the gif below.

#### Possible cause

The path is transformed only once (at `setPath`). This means the local goal is never updated. I think the path should be transformed at every `computeVelocityCommands` call.

pure_pursuit_bug

### PR DESCRIPTION
**Pull request by Rayman**
1. The path should be transformed on every call to
   `computeVelocityCommands`
2. The local goal should be determined from the closest point to the
   robot onwards
3. Add path pruning

Fix #13

I've even got a gif:
Peek 2020-11-20 14-12

### CODE REVIEW

**Comment by SteveMacenski** [comment]
@shrijitsingh99 please review

File: nav2_pure_pursuit_controller/src/pure_pursuit_controller.cpp [hunk 1]
```diff
@@ -20,6 +20,28 @@ using nav2_util::declare_parameter_if_not_declared;
 namespace nav2_pure_pursuit_controller
 {
 
+/**
+ * Find element in iterator with the minimum calculated value
+ */
+template <typename Iter, typename Getter>
+Iter min_by(Iter begin, Iter end, Getter getCompareVal)
+{
+  if (begin == end)
```
Comment (SteveMacenski) [inline nav2_pure_pursuit_controller/src/pure_pursuit_controller.cpp:29]: Use brackets and lint this code

Comment (Rayman) [reply nav2_pure_pursuit_controller/src/pure_pursuit_controller.cpp:29]: Which codestyle are we using? [This one](https://github.com/davetcoleman/roscpp_code_format/blob/master/.clang-format) gives me a very big diff, I think this repo hasn't been formatted yet

Comment (SteveMacenski) [reply nav2_pure_pursuit_controller/src/pure_pursuit_controller.cpp:29]: ament_cpplint and ament_uncrustify

Comment (Rayman) [reply nav2_pure_pursuit_controller/src/pure_pursuit_controller.cpp]: I've uncrustified & fix most ament_cpplint issues. There is one error left, that the copyright messages have the wrong format. I'm not sure what to do about those.

**Review by SteveMacenski — COMMENTED** [review]
Awesome, I have no code-quality issues, just leaving to @shrijitsingh99 to approve the changes

File: nav2_pure_pursuit_controller/src/pure_pursuit_controller.cpp [hunk 2]
```diff
@@ -123,15 +161,15 @@ geometry_msgs::msg::TwistStamped PurePursuitController::computeVelocityCommands(
 
 void PurePursuitController::setPlan(const nav_msgs::msg::Path & path)
 {
-  // Transform global path into the robot's frame
-  global_plan_ = transformGlobalPlan(path);
+  global_plan_ = path;
```
Comment (SteveMacenski) [inline nav2_pure_pursuit_controller/src/pure_pursuit_controller.cpp:164]: Doesn't this need to be transformed into the odometry frame?

Comment (SteveMacenski) [reply nav2_pure_pursuit_controller/src/pure_pursuit_controller.cpp:164]: You removed the transformation function from this

Comment (SteveMacenski) [reply nav2_pure_pursuit_controller/src/pure_pursuit_controller.cpp:164]: Why move it into the compute function?

File: nav2_pure_pursuit_controller/src/pure_pursuit_controller.cpp [hunk 3]
```diff
@@ -85,19 +108,34 @@ geometry_msgs::msg::TwistStamped PurePursuitController::computeVelocityCommands(
...
-    global_plan_.poses.begin(), global_plan_.poses.end(),
-    [&](const auto & global_plan_pose) {
-      return hypot(
-        global_plan_pose.pose.position.x,
-        global_plan_pose.pose.position.y) >= lookahead_dist_;
-    })->pose;
+  auto transformed_plan = transformGlobalPlan(pose);
+
+  // First find the closest pose on the path to the robot
+  auto closest_pose_it =
```
Comment (SteveMacenski) [inline nav2_pure_pursuit_controller/src/pure_pursuit_controller.cpp:114]: Why not use the look ahead distance variable? You do not simply want the closest one.

Comment (SteveMacenski) [reply nav2_pure_pursuit_controller/src/pure_pursuit_controller.cpp:114]: I don't really see the point of separating this into 2 lambdas - can you explain it?

**Review by SteveMacenski — CHANGES_REQUESTED** [review]

**Comment by SteveMacenski** [comment]
I'm not sure Shrijit will get to this so I'll review.

PS: thanks for the comments, that made my life easier. I don't usually program with lambdas so that helped me dissect your intent

File: nav2_pure_pursuit_controller/src/pure_pursuit_controller.cpp (hunk 2 above)
Comment (Rayman) [reply nav2_pure_pursuit_controller/src/pure_pursuit_controller.cpp:164]: I've moved it to compute function to calculate this every tick. The map to odom and odom to map transform could be changing at every moment.

If you transform the path to `base_link`, that makes it easy to calculate this:
```cpp
distance_from_robot=hypot(ps.pose.position.x, ps.pose.position.y)
```
Also determining if the local goal is in front of the robot is just looking at the `x` component.

Both `transformGlobalPlan` and `transformPose` are utility functions that could be shared with dwb local planner, they are very similar.

Is ROS1 these utility functions were found in [local_planner_util](https://github.com/ros-planning/navigation/blob/db50577971b3489e2a693820b53aae198400c443/base_local_planner/src/local_planner_util.cpp) which controllers could reuse, which was very nice.

File: nav2_pure_pursuit_controller/src/pure_pursuit_controller.cpp (hunk 3 above)
Comment (Rayman) [reply nav2_pure_pursuit_controller/src/pure_pursuit_controller.cpp:114]: I hope this figure is making it clear:
nav2 bug explained (1)

Comment (SteveMacenski) [reply nav2_pure_pursuit_controller/src/pure_pursuit_controller.cpp:114]: Ah I see, I've fixed this before in other controllers by removing points from the path as it passes it. So if a point has been passed by the robot, its culled from the path stored in the global_path_ variable so that only current/future points are available. DWA did this as well. Then the look ahead point can only be from the forward motion

Comment (SteveMacenski) [reply nav2_pure_pursuit_controller/src/pure_pursuit_controller.cpp:114]: But I think this is OK then for the tutorial code, but it would be more efficient with those changes if you were actually using this on your robot platform.

Comment (SteveMacenski) [reply nav2_pure_pursuit_controller/src/pure_pursuit_controller.cpp:114]: As an aside, are you using this on your platform? If so, do you think this should be moved out of tutorials and into the main nav2 repo? Any changes you'd want to see made for that?'

That figure is nice as well. If you remove the "previously this point.." arrow, you could upload that to this PR and package README to explain how it works for users. Very useful.

Comment (Rayman) [reply nav2_pure_pursuit_controller/src/pure_pursuit_controller.cpp:114]: I could implement path pruning, but then I would copy the implementation from DWB. Could we design/move this code to a utility library so this package can also use that? I'm also fine with just copying the DWB pruning code in here.

I'm not using this on a platform, but I was very confused why the code from the tutorial didn't work. I think it's better to keep this controller as simple as possible as a tutorial.

I'll update this PR with the figure

Comment (SteveMacenski) [reply nav2_pure_pursuit_controller/src/pure_pursuit_controller.cpp:114]: Lets just copy it, especially if its just staying as tutorial code.

Comment (Rayman) [reply nav2_pure_pursuit_controller/src/pure_pursuit_controller.cpp]: I've copied and adapted the path pruning code from dwb to this package. See the updated gif in the PR. I've changed it a little bit to prune towards the closest point to the robot. This works better with determining the lookahead point.

I've also added a small README.

Let me know what you think.

File: nav2_pure_pursuit_controller/README.md [hunk 4]
```diff
@@ -0,0 +1,11 @@
+# Nav2 Pure pursuit controller
+Tutorial code referenced in https://ros-planning.github.io/navigation2/
```
Comment (SteveMacenski) [inline nav2_pure_pursuit_controller/README.md:2]: navigation.ros.org, but also give the actual URL to the tutorial in question

File: nav2_pure_pursuit_controller/src/pure_pursuit_controller.cpp [hunk 5]
```diff
@@ -123,34 +159,60 @@ geometry_msgs::msg::TwistStamped PurePursuitController::computeVelocityCommands(
...
     costmap->getResolution() / 2.0;
 
+  // First find the closest pose on the path to the robot
+  auto transformation_begin =
+    min_by(
+    global_plan_.poses.begin(), global_plan_.poses.end(),
+    [&robot_pose](const geometry_msgs::msg::PoseStamped & ps) {
+      return euclidean_distance(robot_pose, ps);
+    });
+
```
Comment (SteveMacenski) [inline nav2_pure_pursuit_controller/src/pure_pursuit_controller.cpp:197]: Remove this extra space

File: nav2_pure_pursuit_controller/src/pure_pursuit_controller.cpp [hunk 6]
```diff
@@ -123,34 +159,60 @@ geometry_msgs::msg::TwistStamped PurePursuitController::computeVelocityCommands(
...
+
+  // Find the first pose in the end of the plan that's further than dist_threshold from the robot
```
Comment (SteveMacenski) [inline nav2_pure_pursuit_controller/src/pure_pursuit_controller.cpp:199]: I'm not super clear what this line is supposed to mean. I can't decipher what its aim is.

I think at this point, you have the point in the path closest to the robot, lets call it at index `i`. The simplest thing to me would be to then work backwards from `i` and find the point `i - N` which is behind the robot's current pose on the path by more than 1 costmap cell (so `N` could be `0` or `1`) and then delete all points on the path before `i - N`. 

I see elements of that here but the comments don't make clear to me

Comment (SteveMacenski) [reply nav2_pure_pursuit_controller/src/pure_pursuit_controller.cpp:199]: It looks like you're iterating from `i` to `end` (forward) and I don't know what you want to achieve with that. The over-use of lambdas here makes this very difficult to read.

Comment (SteveMacenski) [reply nav2_pure_pursuit_controller/src/pure_pursuit_controller.cpp:199]: I think this probably also works, but I think the comments need to be updated so that its more immediately clear what direction you're taking to do this. I think there are multiple approaches so letting a reader know which you're using is good. I would think like find the earliest point in the path to keep, and then delete all before it. But I think instead you think like finding all the valid points first and then inverting the removal.

Comment (SteveMacenski) [reply nav2_pure_pursuit_controller/src/pure_pursuit_controller.cpp:199]: It seems more straight forward to me to just look for `i - N`, remove all items before then, and then return the transformed path of `i - end`.

File: nav2_pure_pursuit_controller/README.md (hunk 4 above)
Comment (SteveMacenski) [reply nav2_pure_pursuit_controller/README.md:2]: https://navigation.ros.org/plugin_tutorials/docs/writing_new_nav2controller_plugin.html is the URL :smile:

File: nav2_pure_pursuit_controller/src/pure_pursuit_controller.cpp (hunk 6 above)
Comment (Rayman) [reply nav2_pure_pursuit_controller/src/pure_pursuit_controller.cpp]: These comments are adapted directly from [dwb_local_planner.cpp](https://github.com/ros-planning/navigation2/blob/2d31a8d3346d3a9ba6ab99a94d208bdf5879b413/nav2_dwb_controller/dwb_core/src/dwb_local_planner.cpp#L502). Once we figure out what the comments should say, I'll send a PR to fix them in DWB too.

That comment is indeed wrongly formulated. I've changed it to ` From the closest point, look for the first point that's further then dist_threshold from the robot. These points are definitly outside of the costmap so we won't transform them.` (see also the diff). See also the figure below. I've also reordered the code and changed several other comments.

`transformation_end` is probably an optimization that is needed for dwb. Points outside of the costmap will not be transformed, because DWB could never assign a cost to them.

For the pure pursuit controller this optimization is not needed. We could just transform from closest point to end. Should I change the code to that?

As for the style, I've used lambdas because dwb uses them. I thought that would result in the least review resistance.

nav2 transform explained

File: nav2_pure_pursuit_controller/README.md (hunk 4 above)
Comment (Rayman) [reply nav2_pure_pursuit_controller/README.md]: Fixed

File: nav2_pure_pursuit_controller/src/pure_pursuit_controller.cpp (hunk 5 above)
Comment (Rayman) [reply nav2_pure_pursuit_controller/src/pure_pursuit_controller.cpp:197]: Fixed

File: nav2_pure_pursuit_controller/src/pure_pursuit_controller.cpp [hunk 7]
```diff
@@ -123,56 +159,76 @@ geometry_msgs::msg::TwistStamped PurePursuitController::computeVelocityCommands(
...
+  // First find the closest pose on the path to the robot
+  auto transformation_begin =
+    min_by(
+    global_plan_.poses.begin(), global_plan_.poses.end(),
+    [&robot_pose](const geometry_msgs::msg::PoseStamped & ps) {
+      return euclidean_distance(robot_pose, ps);
+    });
+
+  // From the closest point, look for the first point that's further then dist_threshold from the
+  // robot. These points are definitly outside of the costmap so we won't transform them.
```
Comment (SteveMacenski) [inline nav2_pure_pursuit_controller/src/pure_pursuit_controller.cpp:199]: "definitely"

**Review by SteveMacenski — APPROVED** [review]

File: nav2_pure_pursuit_controller/src/pure_pursuit_controller.cpp (hunk 6 above)
Comment (SteveMacenski) [reply nav2_pure_pursuit_controller/src/pure_pursuit_controller.cpp]: I'm sure DWB has its issues but nothing we can do about that right at this moment. It looks like my interpretation of that code was correct - I don't love it, but I think its fine for now. Not the optimization I would have made, but I think its OK. This will cause issues though if there are users that don't do replanning, but so will DWB so we'll wait until someone says its a problem to solve. The comment helps make it abundantly clear.

Comment (SteveMacenski) [reply nav2_pure_pursuit_controller/src/pure_pursuit_controller.cpp]: Please also update the image to this new one - its a helpful detail.

**Comment by SteveMacenski** [comment]
Fix the typo and we can merge it. Also see https://github.com/ros-planning/navigation2_tutorials/issues/15, I'm seriously considering now moving this to the main repo. It seems like most robotics projects have some form of pure pursuit controller in them - even if its not really what I would recommend. This only really needs a little bit of polish before I think its good enough.

File: nav2_pure_pursuit_controller/src/pure_pursuit_controller.cpp (hunk 7 above)
Comment (Rayman) [reply nav2_pure_pursuit_controller/src/pure_pursuit_controller.cpp]: Fixed

File: nav2_pure_pursuit_controller/src/pure_pursuit_controller.cpp (hunk 6 above)
Comment (Rayman) [reply nav2_pure_pursuit_controller/src/pure_pursuit_controller.cpp]: I've updated the image
